version: "3.7"
services:
  reverse-proxy:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - --api.insecure=true

      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=${NETWORK_NAME-proxy}

      - --providers.file.directory=/etc/traefik/
      - --providers.file.watch=true

      - --entrypoints.web.address=:80

      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true

      # http to https redirect
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.permanent=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.dynamic.yml:/etc/traefik/conf.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    name: ${NETWORK_NAME-proxy}